.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)whereis.1	5.1 (Berkeley) 4/29/85
.\"
.TH WHEREIS 1 "December 15, 2023"
.UC
.SH NAME
whereis \- locate source, binary, and or manual for program
.SH SYNOPSIS
.B whereis
[
.B \-bms
] [
.B \-u
] [
.B \-BMS
dir ...
.B \-f
] name ...
.SH DESCRIPTION
.I whereis
locates source/binary and manuals sections for specified files.
The supplied names are first stripped of leading pathname components
and any (single) trailing extension of the form ``.ext'', e.g. ``.c''.
Prefixes of ``s.'' resulting from use of source code control are also
dealt with.
.I whereis
then attempts to locate the desired program in a list of standard places.
.PP
If any of the
.BR \-b ,
.BR \-m ,
or
.B \-s
flags are given then
.I whereis
searches only for binaries, manual sections, or sources, respectively
(or any two thereof).
.PP
The
.B \-u
flag may be used to search for unusual entries.
A file is said to be unusual if it does not have one entry of
each requested type.
Thus ``whereis \-m \-u *'' asks for those files in the current
directory which have no documentation.
.PP
Finally, the
.BR \-B ,
.BR \-M ,
and
.B \-S
flags may be used to change or otherwise limit the places where
.I whereis
searches.
The
.B \-f
file flag is used to terminate the last such directory list
and signal the start of file names.
.SH EXAMPLES
The following finds all the files in
.I /usr/sbin
which are not documented in
.I /usr/share/man/cat8
with source in
.IR /usr/src/usr.sbin :
.IP
cd /usr/sbin
.br
whereis \-u \-M /usr/share/man/cat8 \-S /usr/src/usr.sbin \-f *
.SH FILES
/usr/src/*
.br
/usr/share/man/*
.br
/etc, /bin. /sbin, /usr/{bin,sbin,games,libexec,local}
.SH AUTHOR
William Joy
.SH BUGS
Since the program uses
.IR chdir (2)
to run faster, pathnames given with
.BR \-B ,
.BR \-M ,
and
.B \-S
must be full pathnames; i.e., they must begin with a ``/''.
